<div class="lwBoxLeftnavi" onClick="changeUrl('admin.php?obj=admin');">zur&uuml;ck</div>

<div class="lwBoxLeftContent">
    <div class="cNavEntry" onclick="changeUrl('?obj=tabletools&module=exporter');"<?php if ($this->module == "exporter"): ?>style="background-color: #0072BB;"<?php endif; ?>> Exporter </div>
    <div class="cNavEntry" onclick="changeUrl('?obj=tabletools&module=importer');"<?php if ($this->module == "importer"): ?>style="background-color: #0072BB;"<?php endif; ?>> Importer </div>
</div>